{% set version = "1.8.0" %}

package:
  name: go-ghq
  version: {{ version }}

source:
  url: https://github.com/x-motemen/ghq/archive/v{{ version }}.tar.gz
  sha256: 76cce5e3b3a39ab37d59138b916cc97d21dd6e98791775bdadc6986624918343

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - ghq --help

about:
  home: https://github.com/x-motemen/ghq
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: ghq provides a way to organize remote repository clones, like go get does.
  dev_url: https://github.com/x-motemen/ghq

extra:
  recipe-maintainers:
    - danielnachun
    - sodre
