{% set name = "ghq" %}
{% set version = "1.6.2" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/x-motemen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 97b2ad74b4ed0879ba60e3d94d5a539481cdf60cfac8f3426aad5b3820a1b830

build:
  number: 0
  script:
    - go install -ldflags "-X main.revision={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - ghq --help

about:
  home: https://github.com/x-motemen/ghq
  license: MIT
  license_file: LICENSE
  summary: ghq provides a way to organize remote repository clones, like go get does.

  dev_url: https://github.com/x-motemen/ghq

extra:
  recipe-maintainers:
    - sodre
