schema_version: 1

context:
  version: "1.11.1"

package:
  name: go-ghq
  version: ${{ version }}

source:
  url: https://github.com/x-motemen/ghq/archive/v${{ version }}.tar.gz
  sha256: 78fe7f2a536cdc1e52907767d53ecebfe4d80a9c6ca404908b24bcaf0bb010de

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - ghq --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: ghq provides a way to organize remote repository clones, like go get does.
  homepage: https://github.com/x-motemen/ghq
  repository: https://github.com/x-motemen/ghq

extra:
  recipe-maintainers:
    - danielnachun
    - sodre
