schema_version: 1

context:
  version: "1.10.1"

package:
  name: go-ghq
  version: ${{ version }}

source:
  url: https://github.com/x-motemen/ghq/archive/v${{ version }}.tar.gz
  sha256: 67ff0fc695ba8d82ab1240c8a7be7106294c3d1493807903d3a49004ae56667a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - ghq --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: ghq provides a way to organize remote repository clones, like go get does.
  homepage: https://github.com/x-motemen/ghq
  repository: https://github.com/x-motemen/ghq

extra:
  recipe-maintainers:
    - danielnachun
    - sodre
