schema_version: 1

context:
  version: "1.9.3"

package:
  name: go-ghq
  version: ${{ version }}

source:
  url: https://github.com/x-motemen/ghq/archive/v${{ version }}.tar.gz
  sha256: 41aa3d2f9338922274e9df76a556671d58b0f365814b0b17790ac893c5e59797

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - ghq --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: ghq provides a way to organize remote repository clones, like go get does.
  homepage: https://github.com/x-motemen/ghq
  repository: https://github.com/x-motemen/ghq

extra:
  recipe-maintainers:
    - danielnachun
    - sodre
